export const permissions = {
  dashboardView: 'Reception.Dashboard.View',
  patientsSearch: 'Patients.Search',
  patientsCreate: 'Patients.Create',
  patientsDemographicsView: 'Patients.Demographics.View',
  patientsDemographicsUpdate: 'Patients.Demographics.Update',
  appointmentsView: 'Appointments.View',
  appointmentsCreate: 'Appointments.Create',
  appointmentsReschedule: 'Appointments.Reschedule',
  appointmentsCancel: 'Appointments.Cancel',
  appointmentsCheckIn: 'Appointments.CheckIn',
  appointmentsNoShow: 'Appointments.MarkNoShow',
  queueView: 'Queue.View',
  queueManage: 'Queue.Manage',
  printPatientCard: 'Print.PatientCard',
  printAppointmentSlip: 'Print.AppointmentSlip',
  adminOverview: 'Admin.Overview.View',
  adminUsersView: 'Admin.Users.View',
  adminUsersManage: 'Admin.Users.Manage',
  adminPatientsManage: 'Admin.Patients.Manage',
  adminAppointmentsManage: 'Admin.Appointments.Manage',
  adminPaymentsManage: 'Admin.Payments.Manage',
  adminBroadcast: 'Admin.Broadcast',
} as const;

export type Permission = (typeof permissions)[keyof typeof permissions];
