import { HospitalLogo } from '../../../components/common/HospitalLogo';
import { useMemo, useState } from 'react';
import { AlertTriangle, Bell, CheckCircle2, ClipboardList, LayoutDashboard, LogOut, Package, Pill, Search, Settings, Truck, Users, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { clearCurrentSession, getCurrentSession } from '../../../auth.service';
import { readDoctorData, writeDoctorData } from '../../doctor/services/doctorStorage';
import { ConfirmDialog } from '../../../components/common/ConfirmDialog';

import type { Prescription, DispensedRecord } from '../../doctor/services/mockData';

const stockItems = [
  { name: 'Amoxicillin 500mg', stock: 18, unit: 'boxes', level: 'low' },
  { name: 'Paracetamol 500mg', stock: 142, unit: 'strips', level: 'good' },
  { name: 'Metformin 500mg', stock: 8, unit: 'boxes', level: 'critical' },
  { name: 'Omeprazole 20mg', stock: 56, unit: 'boxes', level: 'good' },
];

export function PharmacyDashboardPage() {
  const navigate = useNavigate();
  const session = getCurrentSession();
  const [activeView, setActiveView] = useState<'overview' | 'prescriptions' | 'inventory' | 'history'>('overview');
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState<Prescription | null>(null);
  const [message, setMessage] = useState('');
  // Safety: dispensing is irreversible in this workflow, so the final write
  // happens only after a second explicit confirmation.
  const [dispenseNote, setDispenseNote] = useState('');
  const [confirmDispenseOpen, setConfirmDispenseOpen] = useState(false);
  const [prescriptions, setPrescriptions] = useState<Prescription[]>(() => readDoctorData('prescriptions', []));
  const [dispensed, setDispensed] = useState<DispensedRecord[]>(() => readDoctorData('dispensed-prescriptions', []));
  const pending = prescriptions.filter((item) => item.status === 'Pending pharmacist');
  const filtered = useMemo(() => pending.filter((item) => `${item.patientName} ${item.patientMrn} ${item.medicines.map((medicine) => medicine.medicine).join(' ')}`.toLowerCase().includes(query.toLowerCase())), [pending, query]);
  const logout = () => { clearCurrentSession(); navigate('/login', { replace: true }); };
  const dispense = (note: string) => {
    if (!selected) return;
    const record: DispensedRecord = { ...selected, status: 'Dispensed', dispensedAt: new Date().toISOString(), dispensedBy: session?.user.fullName ?? 'Pharmacist', pharmacyNote: note };
    const nextDispensed = [record, ...dispensed]; const nextPending = prescriptions.map((item) => item === selected ? { ...item, status: 'Dispensed' } : item);
    setDispensed(nextDispensed); setPrescriptions(nextPending); writeDoctorData('dispensed-prescriptions', nextDispensed); writeDoctorData('prescriptions', nextPending); setSelected(null); setMessage('Prescription marked as dispensed and saved to pharmacy history.');
  };
  // First step: capture the note and ask for confirmation; the actual
  // dispensing write happens in confirmDispense.
  const requestDispense = (note: string) => {
    setDispenseNote(note);
    setConfirmDispenseOpen(true);
  };
  const confirmDispense = () => {
    setConfirmDispenseOpen(false);
    dispense(dispenseNote);
  };
  const navigation = [['overview', 'Dashboard', LayoutDashboard], ['prescriptions', 'Prescription queue', ClipboardList], ['inventory', 'Inventory', Package], ['history', 'Dispensing history', CheckCircle2]] as const;
  return <div className="min-h-screen bg-[#f4f8fb] text-slate-800"><aside className="fixed inset-y-0 left-0 z-20 hidden w-64 flex-col bg-[#073b4c] px-4 py-5 text-white lg:flex"><div className="flex items-center gap-3 border-b border-white/10 px-1 pb-5"><HospitalLogo /><div><p className="font-bold">Mastan Hospital</p><p className="text-xs text-cyan-100">Pharmacy workspace</p></div></div><div className="mt-7 rounded-2xl bg-white/10 p-4"><p className="text-xs uppercase tracking-wider text-cyan-200">Clinical support</p><p className="mt-1 font-semibold">Pharmacist</p><p className="mt-1 text-xs text-slate-300">Pharmacy Department</p></div><nav className="mt-7 flex-1 space-y-2">{navigation.map(([key, label, Icon]) => <button type="button" key={key} onClick={() => setActiveView(key)} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm ${activeView === key ? 'bg-cyan-400/15 font-semibold text-cyan-100' : 'text-slate-300 hover:bg-white/10'}`}><Icon className="h-5 w-5" />{label}</button>)}</nav><div className="border-t border-white/10 pt-4"><button type="button" className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm text-slate-300 hover:bg-white/10"><Settings className="h-5 w-5" />Settings</button><button type="button" onClick={logout} className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm text-slate-300 hover:bg-white/10"><LogOut className="h-5 w-5" />Sign out</button></div></aside>
    <div className="lg:pl-64"><header className="flex h-20 items-center justify-between border-b border-slate-200 bg-white px-5 sm:px-8"><div className="flex min-w-0 items-center gap-3"><HospitalLogo className="h-12 w-12" /><div><p className="text-sm text-slate-500">Mastan Hospital · Pharmacy</p><h1 className="text-xl font-bold text-slate-900">{navigation.find(([key]) => key === activeView)?.[1]}</h1></div></div><div className="flex items-center gap-4"><Bell className="h-5 w-5 text-slate-500" /><div className="hidden sm:block"><p className="text-sm font-semibold text-slate-900">{session?.user.fullName ?? 'Pharmacist'}</p><p className="text-xs text-slate-500">Pharmacy Department</p></div><div className="flex h-9 w-9 items-center justify-center rounded-full bg-teal-100 text-sm font-bold text-teal-700">PH</div></div></header><main className="mx-auto max-w-7xl p-5 sm:p-8">{activeView === 'overview' ? <Overview pending={pending.length} lowStock={stockItems.filter((item) => item.level !== 'good').length} dispensed={dispensed.filter((item) => new Date(item.dispensedAt).toDateString() === new Date().toDateString()).length} onOpen={(view) => setActiveView(view)} /> : activeView === 'inventory' ? <Inventory /> : activeView === 'history' ? <History records={dispensed} /> : <PrescriptionQueue prescriptions={filtered} query={query} setQuery={setQuery} onSelect={setSelected} />}</main></div>{selected ? <DispenseDialog prescription={selected} onClose={() => setSelected(null)} onDispense={requestDispense} /> : null}<ConfirmDialog open={confirmDispenseOpen} title="Confirm dispensing" description="Dispensing is recorded permanently in pharmacy history. Verify the prescription once more." detail={selected ? <div className="space-y-1 text-sm text-slate-700"><p><span className="font-semibold">Patient:</span> {selected.patientName} ({selected.patientMrn})</p><p><span className="font-semibold">Medicines:</span> {selected.medicines.map((medicine) => medicine.medicine).join(', ')}</p>{dispenseNote ? <p><span className="font-semibold">Note:</span> {dispenseNote}</p> : null}</div> : null} confirmLabel="Dispense now" onConfirm={confirmDispense} onCancel={() => setConfirmDispenseOpen(false)} />{message ? <div className="fixed bottom-5 right-5 flex items-center gap-3 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white shadow-lg"><CheckCircle2 className="h-5 w-5" />{message}<button type="button" onClick={() => setMessage('')} aria-label="Close message"><X className="h-4 w-4" /></button></div> : null}</div>;
}

function Overview({ pending, lowStock, dispensed, onOpen }: { pending: number; lowStock: number; dispensed: number; onOpen: (view: 'prescriptions' | 'inventory' | 'history') => void }) { return <div><div className="rounded-2xl bg-gradient-to-r from-[#0b7180] to-[#0b5669] p-6 text-white shadow-sm sm:p-8"><p className="text-sm text-cyan-100">Good morning, Pharmacy Team</p><h2 className="mt-1 text-2xl font-bold">Safe dispensing, every patient.</h2><p className="mt-2 text-sm text-cyan-50">Review doctor prescriptions, verify medicines, and keep pharmacy operations up to date.</p></div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Pending prescriptions" value={String(pending)} icon={ClipboardList} tone="teal" onClick={() => onOpen('prescriptions')} /><Card label="Low stock alerts" value={String(lowStock)} icon={AlertTriangle} tone="amber" onClick={() => onOpen('inventory')} /><Card label="Dispensed today" value={String(dispensed)} icon={CheckCircle2} tone="emerald" onClick={() => onOpen('history')} /><Card label="Orders in transit" value="03" icon={Truck} tone="blue" onClick={() => onOpen('inventory')} /></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="font-bold text-slate-900">Pharmacy workflow</h3><p className="mt-1 text-sm text-slate-500">Today’s operational priorities</p></div><Pill className="h-5 w-5 text-teal-700" /></div><div className="mt-5 space-y-3"><Step number="01" title="Review pending prescriptions" detail="Verify medicine, dosage, duration, and patient identity." /><Step number="02" title="Prepare and dispense" detail="Record the handover and add pharmacy instructions." /><Step number="03" title="Monitor inventory" detail="Reorder medicines before they reach critical stock." /></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-900">Safety reminders</h3><div className="mt-5 space-y-3 text-sm text-slate-600"><p className="rounded-xl bg-amber-50 p-3 text-amber-800">Confirm patient name and MRN before dispensing.</p><p className="rounded-xl bg-sky-50 p-3 text-sky-800">Do not dispense a prescription that is missing dosage or duration.</p><p className="rounded-xl bg-emerald-50 p-3 text-emerald-800">Record substitutions or counseling notes in the dispense record.</p></div></div></div></div>; }
function Card({ label, value, icon: Icon, tone, onClick }: { label: string; value: string; icon: typeof Pill; tone: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-teal-300"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className={`mt-2 text-3xl font-bold ${tone === 'amber' ? 'text-amber-600' : tone === 'emerald' ? 'text-emerald-600' : tone === 'blue' ? 'text-sky-700' : 'text-teal-700'}`}>{value}</p></div><Icon className="h-5 w-5 text-teal-700" /></div><p className="mt-3 text-xs font-semibold text-slate-400">Open details →</p></button>; }
function Step({ number, title, detail }: { number: string; title: string; detail: string }) { return <div className="flex gap-3"><span className="text-xs font-bold text-teal-700">{number}</span><div><p className="text-sm font-semibold text-slate-900">{title}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div></div>; }
function PrescriptionQueue({ prescriptions, query, setQuery, onSelect }: { prescriptions: Prescription[]; query: string; setQuery: (value: string) => void; onSelect: (prescription: Prescription) => void }) { return <div><div><p className="text-sm font-semibold text-teal-700">Pharmacy workflow</p><h2 className="mt-1 text-3xl font-bold text-slate-900">Prescription queue</h2><p className="mt-2 text-sm text-slate-500">Multi-medicine prescriptions sent by hospital doctors.</p></div><div className="mt-6 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search patient, MRN, or medicine" className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-teal-500" /></div></div>{prescriptions.length ? <div className="divide-y divide-slate-100">{prescriptions.map((prescription, index) => <button type="button" key={`${prescription.patientMrn}-${index}`} onClick={() => onSelect(prescription)} className="flex w-full flex-wrap items-center gap-4 p-5 text-left hover:bg-teal-50"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-teal-100 text-teal-700"><Users className="h-5 w-5" /></div><div className="min-w-[170px] flex-1"><p className="font-semibold text-slate-900">{prescription.patientName}</p><p className="text-xs text-slate-500">{prescription.patientMrn} · {prescription.medicines.length} medicine(s)</p></div><div className="hidden max-w-sm flex-1 text-xs text-slate-500 sm:block">{prescription.medicines.map((medicine) => medicine.medicine).join(' · ')}</div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">Pending review</span></button>)}</div> : <div className="p-10 text-center text-sm text-slate-500">No pending prescriptions. Doctor prescriptions will appear here automatically.</div>}</div></div>; }
function DispenseDialog({ prescription, onClose, onDispense }: { prescription: Prescription; onClose: () => void; onDispense: (note: string) => void }) { const [note, setNote] = useState(''); return <div className="fixed inset-0 z-40 flex items-center justify-center bg-slate-950/40 p-4"><div className="max-h-[90vh] w-full max-w-xl overflow-auto rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-700">Prescription verification</p><h2 className="mt-1 text-2xl font-bold text-slate-900">{prescription.patientName}</h2><p className="text-sm text-slate-500">{prescription.patientMrn}</p></div><button type="button" onClick={onClose} aria-label="Close"><X className="h-5 w-5 text-slate-500" /></button></div><div className="mt-5 space-y-3">{prescription.medicines.map((medicine, index) => <div key={index} className="rounded-xl border border-slate-200 p-4"><p className="font-semibold text-slate-900">{medicine.medicine}</p><p className="mt-1 text-sm text-slate-600">{medicine.dosage} · {medicine.duration || 'Duration not specified'}</p><p className="mt-1 text-xs text-slate-500">{medicine.instructions || 'No special instructions'}</p></div>)}</div><label className="mt-5 block text-sm font-semibold text-slate-700">Pharmacy note<textarea value={note} onChange={(e) => setNote(e.target.value)} rows={3} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-teal-500" placeholder="Counseling, substitution, or handover notes..." /></label><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-600">Cancel</button><button type="button" onClick={() => onDispense(note)} className="flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-3 text-sm font-semibold text-white"><CheckCircle2 className="h-4 w-4" />Mark dispensed</button></div></div></div>; }
function Inventory() { return <div><p className="text-sm font-semibold text-teal-700">Pharmacy operations</p><h2 className="mt-1 text-3xl font-bold text-slate-900">Inventory</h2><p className="mt-2 text-sm text-slate-500">Monitor medicine stock and replenishment needs.</p><div className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="divide-y divide-slate-100">{stockItems.map((item) => <div key={item.name} className="flex flex-wrap items-center gap-4 p-5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-50 text-teal-700"><Package className="h-5 w-5" /></div><div className="flex-1"><p className="font-semibold text-slate-900">{item.name}</p><p className="text-xs text-slate-500">Current stock</p></div><p className="text-sm font-semibold text-slate-700">{item.stock} {item.unit}</p><span className={`rounded-full px-3 py-1 text-xs font-semibold ${item.level === 'critical' ? 'bg-rose-50 text-rose-700' : item.level === 'low' ? 'bg-amber-50 text-amber-700' : 'bg-emerald-50 text-emerald-700'}`}>{item.level === 'good' ? 'Stock healthy' : item.level === 'critical' ? 'Critical' : 'Low stock'}</span></div>)}</div></div></div>; }
function History({ records }: { records: DispensedRecord[] }) { return <div><p className="text-sm font-semibold text-teal-700">Pharmacy operations</p><h2 className="mt-1 text-3xl font-bold text-slate-900">Dispensing history</h2><p className="mt-2 text-sm text-slate-500">Completed prescription handovers recorded by pharmacy.</p><div className="mt-6 space-y-4">{records.length ? records.map((record, index) => <div key={`${record.patientMrn}-${index}`} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold text-slate-900">{record.patientName} · {record.patientMrn}</p><p className="mt-1 text-xs text-slate-500">Dispensed by {record.dispensedBy}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">Dispensed</span></div><p className="mt-3 text-sm text-slate-600">{record.medicines.map((medicine) => medicine.medicine).join(' · ')}</p>{record.pharmacyNote ? <p className="mt-2 text-xs text-slate-500">Note: {record.pharmacyNote}</p> : null}</div>) : <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">No dispensing records yet.</div>}</div></div>; }
