import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { CalendarDays, CheckCircle2, ClipboardList, Download, FileText, Pill, Plus, Save, Search, Send, UserRound, Users } from 'lucide-react';
import { readDoctorData, writeDoctorData } from '../services/doctorStorage';
import type { Prescription } from '../services/mockData';

type PageKind = 'patients' | 'appointments' | 'consultation' | 'records' | 'prescriptions' | 'reports' | 'notifications' | 'profile' | 'settings';
const patients = [['MH-240318', 'Ayesha Khan', '32', 'Female', '09:00 AM', 'Follow-up'], ['MH-240321', 'Muhammad Hamza', '47', 'Male', '09:30 AM', 'New consultation'], ['MH-240327', 'Sana Iqbal', '28', 'Female', '10:00 AM', 'Follow-up'], ['MH-240329', 'Bilal Ahmed', '55', 'Male', '10:30 AM', 'New consultation'], ['MH-240334', 'Nadia Rauf', '41', 'Female', '11:00 AM', 'Follow-up']];
const titles: Record<PageKind, [string, string]> = { patients: ['My patients', 'Search and review patients assigned to your OPD.'], appointments: ['Appointments', 'Manage your consultation schedule and visit status.'], consultation: ['Consultation room', 'Record today’s clinical assessment and treatment plan.'], records: ['Medical records', 'Review patient histories, diagnoses, and clinical notes.'], prescriptions: ['Prescriptions', 'Create and review prescriptions for your patients.'], reports: ['Reports', 'Download summaries of your OPD activity.'], notifications: ['Notifications', 'Stay updated with patient and hospital activity.'], profile: ['My profile', 'Manage your professional information.'], settings: ['Settings', 'Configure your workspace preferences.'] };

export function DoctorWorkspacePage({ kind }: { kind: PageKind }) {
  const navigate = useNavigate(); const [query, setQuery] = useState(''); const [saved, setSaved] = useState(false); const [selectedPatient, setSelectedPatientState] = useState(''); const setSelectedPatient = (name: string) => { setSelectedPatientState(name); const patient = patients.find((item) => item[1] === name); if (patient) navigate(`/doctor/patients/${patient[0]}`); };
  const [title, subtitle] = titles[kind]; const filtered = patients.filter((patient) => patient.join(' ').toLowerCase().includes(query.toLowerCase()));
  if (kind === 'consultation') return <Consultation saved={saved} setSaved={setSaved} />;
  if (kind === 'profile' || kind === 'settings') return <FormPage kind={kind} saved={saved} setSaved={setSaved} />;
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-teal-700">Clinical workspace</p><h2 className="mt-1 text-3xl font-bold text-slate-900">{title}</h2><p className="mt-2 text-sm text-slate-500">{subtitle}</p></div>{['patients', 'appointments', 'prescriptions'].includes(kind) ? <button type="button" onClick={() => navigate('/doctor/consultation')} className="flex items-center justify-center gap-2 rounded-xl bg-teal-700 px-4 py-3 text-sm font-semibold text-white hover:bg-teal-800"><Plus className="h-4 w-4" />{kind === 'prescriptions' ? 'New prescription' : 'Add new'}</button> : null}</div>
    {kind === 'reports' ? <Reports /> : kind === 'notifications' ? <Notifications /> : kind === 'prescriptions' ? <Prescriptions /> : <div className="mt-6 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by name or MRN" className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100" /></div><select className="rounded-xl border border-slate-200 px-3 text-sm text-slate-600"><option>All statuses</option><option>Scheduled</option><option>Completed</option><option>Waiting</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{['Patient / MRN', 'Age / Gender', 'Time', 'Visit type', 'Action'].map((head) => <th key={head} className="px-5 py-3 font-semibold">{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((patient) => <tr key={patient[0]} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-semibold text-slate-900">{patient[1]}</p><p className="text-xs text-slate-500">{patient[0]}</p></td><td className="px-5 py-4 text-slate-600">{patient[2]} years · {patient[3]}</td><td className="px-5 py-4 text-slate-600">{patient[4]}</td><td className="px-5 py-4"><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-semibold text-teal-700">{patient[5]}</span></td><td className="px-5 py-4"><button type="button" onClick={() => setSelectedPatient(patient[1])} className="font-semibold text-teal-700 hover:text-teal-900">{kind === 'appointments' ? 'Open visit' : 'View record'}</button></td></tr>)}</tbody></table></div>{selectedPatient ? <div className="border-t border-emerald-100 bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 className="mr-2 inline h-4 w-4" />{selectedPatient} selected. Clinical workspace is ready.</div> : null}</div>}
  </div>;
}

function Consultation({ saved, setSaved }: { saved: boolean; setSaved: (value: boolean) => void }) { const saveConsultation = () => { writeDoctorData('consultations', [{ patientMrn: 'MH-240318', savedAt: new Date().toISOString(), status: 'Completed' }, ...readDoctorData('consultations', [])]); setSaved(true); }; return <div><div><p className="text-sm font-semibold text-teal-700">Clinical workspace</p><h2 className="mt-1 text-3xl font-bold text-slate-900">Consultation room</h2><p className="mt-2 text-sm text-slate-500">Document a patient visit securely.</p></div><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_1.5fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-900">Select patient</h3><div className="mt-4 space-y-3">{patients.slice(0, 3).map((p, i) => <button key={p[0]} type="button" className={`w-full rounded-xl border p-4 text-left ${i === 0 ? 'border-teal-400 bg-teal-50' : 'border-slate-200 hover:border-teal-300'}`}><p className="font-semibold text-slate-900">{p[1]}</p><p className="mt-1 text-xs text-slate-500">{p[0]} · {p[5]}</p></button>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 pb-4"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-teal-100 font-bold text-teal-700">AK</div><div><h3 className="font-bold text-slate-900">Ayesha Khan</h3><p className="text-xs text-slate-500">MH-240318 · 32 years · Female</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Blood pressure" placeholder="120/80 mmHg" /><Field label="Temperature" placeholder="36.8 °C" /><Field label="Weight" placeholder="65 kg" /><Field label="Pulse" placeholder="72 bpm" /></div><label className="mt-5 block text-sm font-semibold text-slate-700">Clinical notes<textarea rows={4} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-teal-500" placeholder="Enter symptoms, examination findings, and assessment..." /></label><div className="mt-5 flex justify-end"><button type="button" onClick={saveConsultation} className="flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-3 text-sm font-semibold text-white"><Save className="h-4 w-4" />Save consultation</button></div>{saved ? <p className="mt-3 text-right text-sm text-emerald-700">Consultation saved successfully.</p> : null}</section></div></div>; }
function Field({ label, placeholder }: { label: string; placeholder: string }) { return <label className="text-sm font-semibold text-slate-700">{label}<input className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-teal-500" placeholder={placeholder} /></label>; }
function Prescriptions() {
  const navigate = useNavigate();
  const [records] = useState<Prescription[]>(() => readDoctorData('prescriptions', []));
  return <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{records.map((item, index) => <div key={item.id ?? index} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
    <div className="flex items-start justify-between gap-3"><Pill className="h-5 w-5 text-teal-700" /><span className="rounded-full bg-teal-50 px-2 py-1 text-xs text-teal-700">{item.status}</span></div>
    <h3 className="mt-5 font-bold text-slate-900">{item.patientName}</h3><p className="text-xs text-slate-500">{item.patientMrn} ? {new Date(item.createdAt).toLocaleDateString()}</p>
    <div className="mt-4 space-y-3">{item.medicines.map((medicine, medicineIndex) => <div key={medicineIndex}><p className="text-sm font-semibold text-teal-700">{medicine.medicine}</p><p className="mt-1 text-xs text-slate-500">{medicine.dosage} ? {medicine.duration}</p><p className="mt-1 text-xs text-slate-500">{medicine.instructions}</p></div>)}</div>
    <button type="button" onClick={() => navigate('/doctor/consultation')} className="mt-5 text-sm font-semibold text-teal-700">Open consultation</button>
  </div>)}{!records.length ? <p className="text-sm text-slate-500">No prescriptions yet.</p> : null}</div>;
}
function Reports() { return <div className="mt-6 grid gap-4 sm:grid-cols-2">{[['OPD activity summary', 'June 2026 · 84 consultations', CalendarDays], ['Patient outcomes report', 'May 2026 · 67 completed visits', FileText], ['Prescription summary', 'June 2026 · 124 prescriptions', Pill]].map(([name, detail, Icon]) => <div key={String(name)} className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="rounded-xl bg-teal-50 p-3 text-teal-700"><Icon className="h-5 w-5" /></div><div className="flex-1"><h3 className="font-semibold text-slate-900">{name}</h3><p className="mt-1 text-sm text-slate-500">{detail}</p></div><button type="button" aria-label={`Download ${name}`} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Download className="h-5 w-5" /></button></div>)}</div>; }
function Notifications() { return <div className="mt-6 max-w-3xl space-y-3">{['Ayesha Khan has been checked in for your 09:00 AM appointment.', 'New laboratory results are available for MH-240321.', 'Your OPD schedule for tomorrow has been published.', 'Please review the updated hospital clinical documentation policy.'].map((note, i) => <div key={note} className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`mt-1 h-2.5 w-2.5 rounded-full ${i < 2 ? 'bg-teal-500' : 'bg-slate-300'}`} /><div><p className="text-sm text-slate-800">{note}</p><p className="mt-2 text-xs text-slate-400">{i + 1} hour{ i ? 's' : '' } ago</p></div></div>)}</div>; }
function FormPage({ kind, saved, setSaved }: { kind: 'profile' | 'settings'; saved: boolean; setSaved: (value: boolean) => void }) { return <div className="max-w-3xl"><p className="text-sm font-semibold text-teal-700">Account</p><h2 className="mt-1 text-3xl font-bold text-slate-900">{titles[kind][0]}</h2><p className="mt-2 text-sm text-slate-500">{titles[kind][1]}</p><div className="mt-6 space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">{kind === 'profile' ? <><div className="flex items-center gap-4 border-b border-slate-100 pb-5"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-teal-100 text-xl font-bold text-teal-700">DR</div><div><p className="font-bold text-slate-900">Dr. OPD Doctor</p><p className="text-sm text-slate-500">Doctor · Outpatient Department</p></div></div><Field label="Full name" placeholder="Dr. OPD Doctor" /><Field label="Department" placeholder="Outpatient Department" /><Field label="Professional registration number" placeholder="PMDC-000000" /></> : <><Field label="Default appointment view" placeholder="Today’s schedule" /><label className="flex items-center gap-3 text-sm text-slate-700"><input type="checkbox" defaultChecked className="h-4 w-4 accent-teal-700" />Notify me when a patient is checked in</label><label className="flex items-center gap-3 text-sm text-slate-700"><input type="checkbox" defaultChecked className="h-4 w-4 accent-teal-700" />Show completed consultations in my schedule</label></>}<button type="button" onClick={() => setSaved(true)} className="flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-3 text-sm font-semibold text-white"><Save className="h-4 w-4" />Save changes</button>{saved ? <p className="text-sm text-emerald-700">Changes saved successfully.</p> : null}</div></div>; }
