import { useState } from 'react';
import { TestOrders } from '../components/TestOrders';
import { FileImage, Pill, Plus, Save, Send, Stethoscope, Trash2 } from 'lucide-react';
import { readDoctorData, writeDoctorData } from '../services/doctorStorage';

import type { Medicine, Prescription } from '../services/mockData';
type DiagnosticResult = { patientMrn: string; patientName: string; type: 'X-ray' | 'Ultrasound'; study: string; report: string; status: 'Report available' };

const blankMedicine = (): Medicine => ({ medicine: '', dosage: '', duration: '', instructions: '' });

export function DoctorConsultationPage() {
  const [message, setMessage] = useState('');
  const [pharmacy, setPharmacy] = useState('Hospital pharmacy');
  const [medicines, setMedicines] = useState<Medicine[]>([blankMedicine()]);
  const [prescriptions, setPrescriptions] = useState<Prescription[]>(() => readDoctorData('prescriptions', []));
  const [results] = useState<DiagnosticResult[]>(() => readDoctorData('diagnostic-results', []));
  const updateMedicine = (index: number, field: keyof Medicine, value: string) => setMedicines((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const addPrescription = () => {
    const valid = medicines.map((item) => ({ ...item, medicine: item.medicine.trim(), dosage: item.dosage.trim(), duration: item.duration.trim() }));
    if (!valid.length || valid.some((item) => !item.medicine || !item.dosage || !item.duration)) { setMessage('Complete medicine name, dosage and duration for every medicine, or remove the incomplete row.'); return; }
    const item: Prescription = { patientMrn: 'MH-240318', patientName: 'Ayesha Khan', medicines: valid, status: pharmacy === 'Hospital pharmacy' ? 'Pending pharmacist' : 'External prescription', createdAt: new Date().toISOString() };
    const next = [item, ...readDoctorData<Prescription[]>('prescriptions', [])]; try { writeDoctorData('prescriptions', next); } catch { setMessage('Could not save prescription. Please try again.'); return; } setPrescriptions(next); setMedicines([blankMedicine()]); setMessage(pharmacy === 'Hospital pharmacy' ? `${valid.length} medicines sent to the pharmacist queue.` : 'Outside-pharmacy prescription saved.');
  };
  return <div><div><p className="flex items-center gap-2 text-sm font-semibold text-teal-700"><Stethoscope className="h-4 w-4" />Clinical workspace</p><h2 className="mt-1 text-3xl font-bold text-slate-900">Consultation room</h2><p className="mt-2 text-sm text-slate-500">Complete the consultation and coordinate pharmacy and diagnostic services.</p></div><div className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 pb-4"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-teal-100 font-bold text-teal-700">AK</div><div><h3 className="font-bold text-slate-900">Ayesha Khan</h3><p className="text-xs text-slate-500">MH-240318 · 32 years · Female</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-4"><Field label="Blood pressure" placeholder="120/80 mmHg" /><Field label="Temperature" placeholder="36.8 °C" /><Field label="Weight" placeholder="65 kg" /><Field label="Pulse" placeholder="72 bpm" /><Field label="Height" placeholder="6'2 feets" /></div><label className="mt-5 block text-sm font-semibold text-slate-700">Clinical notes<textarea rows={3} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-teal-500" placeholder="Symptoms, examination findings, and assessment..." /></label><button type="button" onClick={() => { writeDoctorData('consultations', [{ patientMrn: 'MH-240318', status: 'Completed', savedAt: new Date().toISOString() }, ...readDoctorData('consultations', [])]); setMessage('Consultation saved.'); }} className="mt-4 flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-3 text-sm font-semibold text-white"><Save className="h-4 w-4" />Save consultation</button></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 font-bold text-slate-900"><Pill className="h-5 w-5 text-teal-700" />Prescribe medicines</h3><p className="mt-1 text-sm text-slate-500">Add all medicines for this prescription before sending it.</p><label className="mt-4 block text-sm font-semibold">Pharmacy<select value={pharmacy} onChange={(e) => setPharmacy(e.target.value)} className="mt-2 w-full rounded-lg border p-2"><option>Hospital pharmacy</option><option>Outside pharmacy</option></select></label><div className="mt-5 space-y-4">{medicines.map((item, index) => <div key={index} className="rounded-xl border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between"><p className="text-sm font-bold text-slate-700">Medicine {index + 1}</p>{medicines.length > 1 ? <button type="button" onClick={() => setMedicines(medicines.filter((_, itemIndex) => itemIndex !== index))} className="rounded-lg p-2 text-rose-500 hover:bg-rose-50" aria-label={`Remove medicine ${index + 1}`}><Trash2 className="h-4 w-4" /></button> : null}</div><div className="grid gap-3 sm:grid-cols-2"><Field label="Medicine" placeholder="e.g. Amoxicillin 500mg" value={item.medicine} onChange={(value) => updateMedicine(index, 'medicine', value)} /><Field label="Dosage" placeholder="1 capsule, 3 times daily" value={item.dosage} onChange={(value) => updateMedicine(index, 'dosage', value)} /><Field label="Duration" placeholder="e.g. 5 days" value={item.duration} onChange={(value) => updateMedicine(index, 'duration', value)} /><Field label="Instructions" placeholder="After meals" value={item.instructions} onChange={(value) => updateMedicine(index, 'instructions', value)} /></div></div>)}</div><div className="mt-4 flex flex-wrap gap-3"><button type="button" onClick={() => setMedicines([...medicines, blankMedicine()])} className="flex items-center gap-2 rounded-xl border border-teal-200 px-4 py-3 text-sm font-semibold text-teal-700 hover:bg-teal-50"><Plus className="h-4 w-4" />Add another medicine</button><button type="button" onClick={addPrescription} className="flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-3 text-sm font-semibold text-white hover:bg-teal-800"><Send className="h-4 w-4" />Save prescription</button></div>{prescriptions.length ? <p className="mt-4 text-xs text-slate-500">{prescriptions.filter((item) => item.patientMrn === 'MH-240318').length} prescription(s) saved for this patient.</p> : null}</section>
      <TestOrders patientMrn="MH-240318" patientName="Ayesha Khan" /></div>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 font-bold text-slate-900"><FileImage className="h-5 w-5 text-teal-700" />Returned diagnostic reports</h3><p className="mt-1 text-sm text-slate-500">Reports returned by X-ray and Ultrasound staff appear here.</p><div className="mt-4 space-y-3">{results.some((item) => item.patientMrn === 'MH-240318') ? results.filter((item) => item.patientMrn === 'MH-240318').map((result) => <div key={`${result.patientMrn}-${result.study}`} className="rounded-xl border border-emerald-100 bg-emerald-50 p-4"><p className="font-semibold text-slate-900">{result.study}</p><p className="text-xs text-slate-500">{result.type} · {result.patientName} · {result.patientMrn}</p><p className="mt-3 text-sm text-slate-700">{result.report}</p></div>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No returned reports yet.</p>}</div></section>{message ? <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-medium text-emerald-700">{message}</p> : null}</div>;
}

function Field({ label, placeholder, value, onChange }: { label: string; placeholder: string; value?: string; onChange?: (value: string) => void }) { return <label className="text-sm font-semibold text-slate-700">{label}<input value={value} onChange={onChange ? (e) => onChange(e.target.value) : undefined} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-teal-500" placeholder={placeholder} /></label>; }
