import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { CalendarDays, CheckCircle2, FileText, HeartPulse, Save } from 'lucide-react';
import { readDoctorData, writeDoctorData } from '../services/doctorStorage';

const months = ['Month 1', 'Month 2', 'Month 3', 'Month 4', 'Month 5', 'Month 6'];
export function GynaeCyclePage() {
  const { patientId = 'MH-240318' } = useParams();
  const patientName = patientId === 'MH-240318' ? 'Ayesha Khan' : 'Patient';
  const storageKey = `gynae-cycle-${patientId}`;
  const [saved, setSaved] = useState(() => readDoctorData(`${storageKey}-saved`, false));
  const [notes, setNotes] = useState(() => readDoctorData(`${storageKey}-notes`, ''));
  const save = () => { writeDoctorData(`${storageKey}-saved`, true); writeDoctorData(`${storageKey}-notes`, notes); setSaved(true); };
  return <div><p className="flex items-center gap-2 text-sm font-semibold text-pink-700"><HeartPulse className="h-4 w-4" />Patient Gynae Care</p><h2 className="mt-1 text-3xl font-bold text-slate-900">{patientName} · Six-month cycle</h2><p className="mt-2 text-sm text-slate-500">Patient-specific antenatal visits, investigations, scans, reports, and clinical milestones.</p><div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric label="Patient" value={patientId} /><Metric label="Reports pending" value="02" /><Metric label="Upcoming scans" value="01" /></div><section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-900">{patientName}’s cycle timeline</h3><div className="mt-5 grid gap-3 md:grid-cols-6">{months.map((month, index) => <div key={month} className={`rounded-xl border p-4 ${index === 2 ? 'border-pink-300 bg-pink-50' : 'border-slate-200'}`}><p className="text-xs font-semibold text-slate-500">{month}</p><p className="mt-2 text-sm font-bold text-slate-900">{index < 3 ? 'Completed' : index === 3 ? 'In progress' : 'Upcoming'}</p><div className="mt-3 h-1.5 rounded-full bg-slate-100"><div className={`h-1.5 rounded-full bg-pink-500 ${index < 3 ? 'w-full' : index === 3 ? 'w-1/2' : 'w-0'}`} /></div></div>)}</div></section><div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 font-bold text-slate-900"><CalendarDays className="h-5 w-5 text-pink-600" />Investigation schedule</h3><div className="mt-4 space-y-3">{['CBC and blood group — Month 1', 'Dating ultrasound — Month 2', 'Anomaly scan — Month 3', 'Growth scan and glucose test — Month 5'].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm text-slate-700"><CheckCircle2 className="h-4 w-4 text-emerald-600" />{item}</div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 font-bold text-slate-900"><FileText className="h-5 w-5 text-pink-600" />Patient cycle notes</h3><textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows={5} className="mt-4 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-pink-500" placeholder="Record this patient’s observations, risk factors, reports, and follow-up plan..." /><button type="button" onClick={save} className="mt-3 flex items-center gap-2 rounded-xl bg-pink-700 px-4 py-3 text-sm font-semibold text-white"><Save className="h-4 w-4" />Save patient cycle</button>{saved ? <p className="mt-3 text-sm text-emerald-700">Patient cycle record saved.</p> : null}</section></div></div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-pink-700">{value}</p></div>; }
