import { useState } from 'react';
import { Baby, CalendarDays, CheckCircle2, ClipboardList, Ruler, Save, Syringe } from 'lucide-react';
import { readDoctorData, writeDoctorData } from '../services/doctorStorage';

const children = [['CH-10021', 'Hamza Ali', '4 years', '09:15 AM', 'Follow-up'], ['CH-10024', 'Emaan Khan', '2 years', '09:45 AM', 'Vaccination'], ['CH-10029', 'Rayyan Ahmed', '7 years', '10:15 AM', 'New consultation'], ['CH-10031', 'Maira Fatima', '9 months', '10:45 AM', 'Growth review']];
export function PediatricDashboardPage() {
  const [saved, setSaved] = useState(() => readDoctorData('pediatric-note-saved', false));
  const save = () => { writeDoctorData('pediatric-note-saved', true); setSaved(true); };
  return <div><p className="flex items-center gap-2 text-sm font-semibold text-sky-700"><Baby className="h-4 w-4" />Paediatrics</p><h2 className="mt-1 text-3xl font-bold text-slate-900">Child Doctor dashboard</h2><p className="mt-2 text-sm text-slate-500">Manage child consultations, growth milestones, vaccination schedules, and pediatric follow-ups.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Today’s children" value="16" /><Metric label="Waiting" value="04" /><Metric label="Vaccinations due" value="07" /><Metric label="Growth reviews" value="05" /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h3 className="font-bold text-slate-900">Today’s pediatric appointments</h3><p className="mt-1 text-sm text-slate-500">Child patients assigned to you</p></div><CalendarDays className="h-5 w-5 text-sky-700" /></div><div className="divide-y divide-slate-100">{children.map((child) => <div key={child[0]} className="flex flex-wrap items-center gap-4 p-5 hover:bg-slate-50"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-sky-50 text-sky-700"><Baby className="h-5 w-5" /></div><div className="min-w-[150px] flex-1"><p className="font-semibold text-slate-900">{child[1]}</p><p className="text-xs text-slate-500">{child[0]} · {child[2]}</p></div><p className="text-sm text-slate-600">{child[3]}</p><span className="rounded-full bg-sky-50 px-3 py-1 text-xs font-semibold text-sky-700">{child[4]}</span></div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-900">Pediatric quick actions</h3><div className="mt-4 space-y-3"><Action icon={Ruler} title="Growth assessment" detail="Record height, weight, and milestones" /><Action icon={Syringe} title="Vaccination schedule" detail="Review upcoming immunizations" /><Action icon={ClipboardList} title="Parent instructions" detail="Prepare follow-up guidance" /></div><button type="button" onClick={save} className="mt-5 flex items-center gap-2 rounded-xl bg-sky-700 px-4 py-3 text-sm font-semibold text-white"><Save className="h-4 w-4" />Save pediatric notes</button>{saved ? <p className="mt-3 flex items-center gap-2 text-sm text-emerald-700"><CheckCircle2 className="h-4 w-4" />Notes saved</p> : null}</section></div></div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-sky-700">{value}</p></div>; }
function Action({ icon: Icon, title, detail }: { icon: typeof Ruler; title: string; detail: string }) { return <button type="button" className="flex w-full items-center gap-3 rounded-xl border border-slate-200 p-3 text-left hover:border-sky-300 hover:bg-sky-50"><Icon className="h-5 w-5 text-sky-700" /><span><p className="text-sm font-semibold text-slate-900">{title}</p><p className="text-xs text-slate-500">{detail}</p></span></button>; }
