import type { AppointmentRecord, DashboardSummary, NotificationItem, PatientDetail, PatientRecord, QueueItem } from '../types';

export const dashboardSummary: DashboardSummary = {
  registrationsToday: 18,
  appointmentsToday: 24,
  waitingPatients: 11,
  checkedInPatients: 8,
  walkInPatients: 5,
  cancelledAppointments: 2,
  noShows: 3,
  pendingPayments: 7,
};

export const appointments: AppointmentRecord[] = [
  {
    id: 'apt-1',
    tokenNumber: 101,
    appointmentTime: '08:30',
    patientName: 'Ayesha Khan',
    mrn: 'MH-2026-000123',
    doctor: 'Dr. Farhan Ali',
    department: 'General Medicine',
    appointmentType: 'Follow-up',
    status: 'Checked In',
    paymentStatus: 'Pending',
  },
  {
    id: 'apt-2',
    tokenNumber: 102,
    appointmentTime: '09:00',
    patientName: 'Bilal Ahmed',
    mrn: 'MH-2026-000124',
    doctor: 'Dr. Saima Noor',
    department: 'Pediatrics',
    appointmentType: 'New Consultation',
    status: 'Waiting',
    paymentStatus: 'Paid',
  },
  {
    id: 'apt-3',
    tokenNumber: 103,
    appointmentTime: '09:30',
    patientName: 'Sara Majeed',
    mrn: 'MH-2026-000125',
    doctor: 'Dr. Hina Shah',
    department: 'Gynecology',
    appointmentType: 'Vaccination',
    status: 'Scheduled',
    paymentStatus: 'Pending',
  },
  {
    id: 'apt-4',
    tokenNumber: 104,
    appointmentTime: '10:00',
    patientName: 'Kamran Yusuf',
    mrn: 'MH-2026-000126',
    doctor: 'Dr. Nadeem Qureshi',
    department: 'Orthopedics',
    appointmentType: 'Procedure-related',
    status: 'Confirmed',
    paymentStatus: 'Paid',
  },
  {
    id: 'apt-5',
    tokenNumber: 105,
    appointmentTime: '10:45',
    patientName: 'Hina Bibi',
    mrn: 'MH-2026-000127',
    doctor: 'Dr. Saima Noor',
    department: 'Pediatrics',
    appointmentType: 'Emergency referral',
    status: 'No Show',
    paymentStatus: 'Pending',
  },
];

export const queueItems: QueueItem[] = [
  {
    id: 'q-1',
    tokenNumber: 45,
    patientName: 'Nadia Ali',
    mrn: 'MH-2026-000126',
    department: 'General Medicine',
    doctor: 'Dr. Farhan Ali',
    priority: 'Urgent',
    status: 'Waiting',
    waitingDuration: '18 mins',
  },
  {
    id: 'q-2',
    tokenNumber: 46,
    patientName: 'Muneeb Raza',
    mrn: 'MH-2026-000127',
    department: 'Pediatrics',
    doctor: 'Dr. Saima Noor',
    priority: 'Normal',
    status: 'Checked In',
    waitingDuration: '10 mins',
  },
  {
    id: 'q-3',
    tokenNumber: 47,
    patientName: 'Farah Jamil',
    mrn: 'MH-2026-000128',
    department: 'Gynecology',
    doctor: 'Dr. Hina Shah',
    priority: 'Pregnant',
    status: 'Waiting',
    waitingDuration: '24 mins',
  },
  {
    id: 'q-4',
    tokenNumber: 48,
    patientName: 'Abdul Wahab',
    mrn: 'MH-2026-000129',
    department: 'Orthopedics',
    doctor: 'Dr. Nadeem Qureshi',
    priority: 'Elderly',
    status: 'Waiting',
    waitingDuration: '16 mins',
  },
];

export const patients: PatientRecord[] = [
  {
    id: 'p-1',
    mrn: 'MH-2026-000123',
    fullName: 'Ayesha Khan',
    age: 31,
    gender: 'Female',
    mobile: '0300-1234567',
    guardianName: 'Khan Ahmed',
    registrationDate: '2026-07-20',
    status: 'Active',  },
  {
    id: 'p-2',
    mrn: 'MH-2026-000124',
    fullName: 'Bilal Ahmed',
    age: 8,
    gender: 'Male',
    mobile: '0333-7654321',
    guardianName: 'Rashid Ahmed',
    registrationDate: '2026-07-21',
    status: 'Active',  },
  {
    id: 'p-3',
    mrn: 'MH-2026-000125',
    fullName: 'Sara Majeed',
    age: 27,
    gender: 'Female',
    mobile: '0345-9911223',
    guardianName: 'Majeedullah',
    registrationDate: '2026-07-22',
    status: 'Active',  },
  {
    id: 'p-4',
    mrn: 'MH-2026-000128',
    fullName: 'Farah Jamil',
    age: 29,
    gender: 'Female',
    mobile: '0312-4456677',
    guardianName: 'Jamil Ahmed',
    registrationDate: '2026-07-23',
    status: 'Active',  },
  {
    id: 'p-5',
    mrn: 'MH-2026-000129',
    fullName: 'Abdul Wahab',
    age: 69,
    gender: 'Male',
    mobile: '0321-7891234',
    guardianName: 'Noor Wahab',
    registrationDate: '2026-07-23',
    status: 'Active',  },
];

export const patientDetails: Record<string, PatientDetail> = {
  'p-1': {
    id: 'p-1',
    mrn: 'MH-2026-000123',
    fullName: 'Ayesha Khan',
    age: 31,
    gender: 'Female',
    mobile: '0300-1234567',
    guardianName: 'Khan Ahmed',
    registrationDate: '2026-07-20',
    status: 'Active',    dob: '1995-03-14',
    address: 'House 12, Block B, Khokhrapar',
    email: 'ayesha@example.com',
    guardianMobile: '0300-5556677',
    registrationType: 'OPD',
    department: 'General Medicine',
    caseSummary: 'Abdominal pain with recent fever and nausea',
    caseDoctors: ['Dr. Farhan Ali', 'Dr. Saima Noor'],
    reports: [
      {
        id: 'r-1',
        title: 'Complete Blood Count',
        type: 'Lab',
        date: '2026-07-25',
        status: 'Completed',
        fileName: 'cbc-ayesha.pdf',
        fileUrl: '/reports/cbc-ayesha.pdf',
      },
      {
        id: 'r-2',
        title: 'Abdominal Ultrasound',
        type: 'Scan',
        date: '2026-07-24',
        status: 'Reviewed',
        fileName: 'abdominal-ultrasound.pdf',
        fileUrl: '/reports/abdominal-ultrasound.pdf',
      },
    ],
  },
  'p-2': {
    id: 'p-2',
    mrn: 'MH-2026-000124',
    fullName: 'Bilal Ahmed',
    age: 8,
    gender: 'Male',
    mobile: '0333-7654321',
    guardianName: 'Rashid Ahmed',
    registrationDate: '2026-07-21',
    status: 'Active',    dob: '2018-01-10',
    address: 'Flat 3, Lane 4, Malir',
    email: 'bilal@example.com',
    guardianMobile: '0315-9988776',
    registrationType: 'Walk-In',
    department: 'Pediatrics',
    caseSummary: 'High fever and cough in pediatric patient',
    caseDoctors: ['Dr. Saima Noor', 'Dr. Hina Shah'],
    reports: [
      {
        id: 'r-3',
        title: 'Urine Analysis',
        type: 'Lab',
        date: '2026-07-23',
        status: 'Completed',
        fileName: 'urine-analysis-bilal.pdf',
        fileUrl: '/reports/urine-analysis-bilal.pdf',
      },
      {
        id: 'r-4',
        title: 'Pediatric Chest X-Ray',
        type: 'X-ray',
        date: '2026-07-24',
        status: 'Reviewed',
        fileName: 'chest-xray-bilal.jpg',
        fileUrl: '/reports/chest-xray-bilal.jpg',
      },
    ],
  },
  'p-4': {
    id: 'p-4',
    mrn: 'MH-2026-000128',
    fullName: 'Farah Jamil',
    age: 29,
    gender: 'Female',
    mobile: '0312-4456677',
    guardianName: 'Jamil Ahmed',
    registrationDate: '2026-07-23',
    status: 'Active',    dob: '1997-09-04',
    address: 'House 88, Gulshan-e-Iqbal',
    email: 'farah@example.com',
    guardianMobile: '0308-9112233',
    registrationType: 'Emergency',
    department: 'Gynecology',
    caseSummary: 'Lower abdominal pain and urgent gynecology review',
    caseDoctors: ['Dr. Hina Shah', 'Dr. Nadeem Qureshi'],
    reports: [
      {
        id: 'r-5',
        title: 'Complete Blood Count',
        type: 'Lab',
        date: '2026-07-24',
        status: 'Completed',
        fileName: 'cbc-report-farah.pdf',
        fileUrl: '/reports/cbc-report-farah.pdf',
      },
      {
        id: 'r-6',
        title: 'Chest X-Ray',
        type: 'X-ray',
        date: '2026-07-24',
        status: 'Reviewed',
        fileName: 'chest-xray-farah.jpg',
        fileUrl: '/reports/chest-xray-farah.jpg',
      },
    ],
  },
};

export const notifications: NotificationItem[] = [
  {
    id: 'n-1',
    title: 'Doctor schedule change',
    detail: 'Dr. Farhan Ali is unavailable after 12 noon.',
    severity: 'warning',
  },
  {
    id: 'n-2',
    title: 'Queue delay',
    detail: 'General Medicine queue is running 15 minutes behind.',
    severity: 'info',
  },
  {
    id: 'n-3',
    title: 'Duplicate patient warning',
    detail: 'A similar record was reviewed and cleared for follow-up.',
    severity: 'warning',
  },
  {
    id: 'n-4',
    title: 'Department closure',
    detail: 'Orthopedics will be temporarily unavailable for 30 minutes.',
    severity: 'critical',
  },
];
